INSERT INTO "Provinces" VALUES
    (1,'Esmeraldas'),
    (2,'Carchi'),
    (3,'Imbabura'),
    (4,'Sucumbíos'),
    (5,'Manabí'),
    (6,'Santo Domingo de los Tsáchilas'),
    (7,'Pichincha'),
    (8,'Napo'),
    (9,'Orellana'),
    (10,'Pastaza'),
    (11,'Los Ríos'),
    (12,'Cotopaxi'),
    (13,'Bolívar'),
    (14,'Tungurahua'),
    (15,'Chimborazo'),
    (16,'Morona Santiago'),
    (17,'Guayas'),
    (18,'Santa Elena'),
    (19,'Cañar'),
    (20,'Azuay'),
    (21,'El Oro'),
    (22,'Loja'),
    (23,'Zamora Chinchipe'),
    (24,'Galápagos');